import assert from 'node:assert/strict';
import { applyPatches, trustedBase, textParts, messages, turnRequest, Desktop } from '../src/bridge.mjs';
let s = { list: [{ text: '你' }] };
s = applyPatches(s, [{ op: 'replace', path: ['list', 0, 'text'], value: '你好' }, { op: 'add', path: ['list', '-'], value: { text: '世界' } }]);
assert.deepEqual(s.list.map(x => x.text), ['你好', '世界']);
assert.deepEqual(applyPatches(s, [{ op: 'remove', path: ['list', 0] }]).list, [{ text: '世界' }]);
assert.throws(() => applyPatches({}, [{ op: 'add', path: ['__proto__', 'bad'], value: 1 }]));
assert.equal({}.bad, undefined);
assert.equal(trustedBase('https://ilinkai.weixin.qq.com/'), 'https://ilinkai.weixin.qq.com');
for (const bad of ['http://ilinkai.weixin.qq.com', 'https://weixin.qq.com.evil.test', 'https://user@ilinkai.weixin.qq.com', 'https://ilinkai.weixin.qq.com:4431']) assert.throws(() => trustedBase(bad));
assert.deepEqual(textParts('你😀好🌱', 2), ['你😀', '好🌱']);
const state = { turnHistory: { kind: 'canonical', history: { entitiesByKey: { a: { turnStartedAtMs: 1, status: 'inProgress', items: [{ type: 'userMessage', id: 'u', clientId: 'wx', content: [{ type: 'text', text: '你好' }] }, { type: 'agentMessage', id: 'a', text: '收到', phase: 'commentary' }] } } } } };
assert.deepEqual(messages(state).map(x => [x.role, x.text, x.done]), [['user', '你好', true], ['assistant', '收到', false]]);
const req = turnRequest('thread', '来自微信', 'unique');
assert.equal(req.turnStart.request.threadId, req.conversationId);
assert.equal(req.turnStart.request.input[0].text, '来自微信');
assert.equal(req.turnStart.request.approvalPolicy, undefined);
let calls = 0;
const d = new Desktop('thread', () => calls++); d.owner = 'owner'; d.write = () => {};
const event = { type: 'broadcast', sourceClientId: 'owner', method: 'thread-stream-state-changed', version: 11, params: { conversationId: 'thread', change: { type: 'snapshot', revision: 1, conversationState: structuredClone(state) } } };
d.receive({ ...event, sourceClientId: 'other' }); assert.equal(calls, 0);
d.receive(event); assert.equal(calls, 1);
d.receive({ ...event, params: { ...event.params, change: { type: 'patches', baseRevision: 1, revision: 2, patches: [{ op: 'replace', path: ['turnHistory', 'history', 'entitiesByKey', 'a', 'items', 1, 'text'], value: '收到，正在处理' }] } } });
assert.equal(messages(d.state)[1].text, '收到，正在处理');
d.receive({ ...event, params: { ...event.params, change: { type: 'patches', baseRevision: 0, revision: 3, patches: [] } } });
assert.equal(d.state, null); // Missing revisions trigger a fresh snapshot, never silently skip messages.
console.log('通过：会话增量、版本缺口恢复、来源隔离、微信域名校验、中文分段和发送请求。');
const { command, selectedThread, pageText } = await import('../src/threads.mjs');
assert.deepEqual(command('会话列表'), { kind: 'list' });
assert.deepEqual(command('切换 9'), { kind: 'select', value: '9' });
assert.deepEqual(command('搜索 登录问题'), { kind: 'search', query: '登录问题' });
assert.equal(command('请帮我切换数据库'), null);
const catalog = Array.from({ length: 10 }, (_, i) => ({ id: `thread-${i}`, title: `历史会话 ${i}`, archived: i === 9 }));
assert.equal(selectedThread(catalog, '9').id, 'thread-8');
assert.throws(() => selectedThread(catalog, '0'));
assert.throws(() => selectedThread(catalog, '11'));
assert.match(pageText(catalog, 1, 'thread-8'), /9\. 【当前】\[未归属项目\] 历史会话 8/);
assert.match(pageText(catalog, 1, 'thread-8'), /10\. 【归档】\[未归属项目\] 历史会话 9/);
assert.throws(() => pageText(catalog, 2, 'thread-8'));
console.log('通过：指令解析、分页、全局编号、归档标记、无效编号及普通聊天隔离。');

assert.deepEqual(command('查看会话列表'), { kind: 'list' });

const { thinkingTurn } = await import('../src/bridge.mjs');
const busy = { turns: [{ turnId: 'turn-1', status: 'inProgress', items: [{type:'agentMessage', phase:'final', text:'还在输出'}] }] };
assert.equal(thinkingTurn(busy), 'turn-1');
assert.equal(thinkingTurn({...busy, requests:[{id:'approval'}]}), null);
assert.equal(thinkingTurn({turns:[{turnId:'turn-1',status:'completed'}]}), null);
assert.equal(thinkingTurn(null), null);
assert.equal(thinkingTurn({turnHistory:{kind:'canonical',history:{entitiesByKey:{x:busy.turns[0]}}}}), 'turn-1');
console.log('通过：处理中状态、流式回复未完成、审批暂停、完成停止和断线停止。');

const { projectFor, projectPageText } = await import('../src/threads.mjs');
const { validateConfig } = await import('../src/settings.mjs');
const projects = [{id:'root',label:'工程',path:'/work/app'},{id:'nested',label:'子工程',path:'/work/app/sub'}];
assert.equal(projectFor('/work/app/sub/src',projects).projectId,'nested');
assert.equal(projectFor('/work/application',projects).projectId,null);
assert.equal(projectFor(undefined,projects).projectId,null);
assert.match(projectPageText([{id:'root',label:'工程',count:2}]),/工程（2 个会话）/);
assert.deepEqual(command('项目列表'),{kind:'projects'});
assert.deepEqual(command('2','projects'),{kind:'number',value:'2'});
assert.deepEqual(command('2','threads'),{kind:'number',value:'2'});
assert.equal(command('2','chat'),null);
assert.deepEqual(command('查看项目 2'),{kind:'project',value:'2'});
const valid={threadId:'11111111-1111-4111-8111-111111111111',projects};
assert.equal(validateConfig(valid),valid);
assert.throws(()=>validateConfig({...valid,threadId:'not-an-id'}));
assert.throws(()=>validateConfig({...valid,projects:[projects[0],projects[0]]}));
assert.throws(()=>validateConfig({...valid,projects:[{id:'p',label:'p',path:'relative'}]}));
console.log('通过：项目路径边界、子项目优先、数字菜单上下文和配置校验。');
